apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "s3-tech-adapter.labels" . | nindent 4 }}
  name: {{ template "s3-tech-adapter.fullname" . }}-config
data:
  application.yml: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.yml" | nindent 4 }}
  {{ end }}
  {{- if .Values.kmsPolicyOverride -}}
  kmsPolicy.json: |
  {{- .Values.kmsPolicyOverride | nindent 4 }}
  {{ end }}
  {{- if .Values.bucketPolicyOverride -}}
  bucketPolicy.json: |
  {{- .Values.bucketPolicyOverride | nindent 4 }}
  {{ end }}
